### ISSUE TITLE
report deprecation errors, when a nette file references a `@deprecated` class

### ISSUE THREAD

**Issue by staabm** [phpstan/phpstan-nette#103]
would it be possible to have a new Rule which reports errors when nette-config files reference classes which are `@deprecated`.

this would help to provide a smoother migration path for packages which distribute phpstan extensions via .neon files.

see also https://github.com/symplify/symplify/issues/4169 for a related problems discussion about BC breaking changes in phpstan context.

**Comment by ondrejmirtes** [comment]
No idea what you're talking about, can you provide an example?

**Comment by staabm** [comment]
a project which references class from a different package in a .neon file like e.g.

```
services:
    -
        class: Symplify\PHPStanRules\CognitiveComplexity\Rules\FunctionLikeCognitiveComplexityRule
        tags: [phpstan.rules.rule]
        arguments:
            maxMethodCognitiveComplexity: 8
```

would be interessted whether the class `Symplify\PHPStanRules\CognitiveComplexity\Rules\FunctionLikeCognitiveComplexityRule`  is considered deprecated and might go away in a future release (or a alternative should be used).

when such file is only referenced in .neon files, noone see a error otherwise anywhere.
